# Generated by Django 5.0.7 on 2024-08-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('release_date', models.CharField(max_length=4)),
                ('imdb_rating', models.FloatField()),
                ('duration', models.FloatField()),
            ],
        ),
    ]
