# Generated by Django 5.0.7 on 2024-08-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_movie_created_by_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
