# Generated by Django 5.0.7 on 2024-08-04 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_movie_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_by',
            field=models.ManyToManyField(blank=True, related_name='updated_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
